apiVersion: v1
kind: ConfigMap
metadata:
  name: "config-{{ .Values.app.name }}"
  namespace: {{ .Release.Namespace }}
data:
  # DATABASE_HOST: {{ .Values.env.DATABASE_HOST | quote }}
  DATABASE_PORT: {{ .Values.env.DATABASE_PORT | quote }}
  DATABASE_NAME: {{ .Values.env.DATABASE_NAME | quote }}
  DATABASE_USER: {{ .Values.env.DATABASE_USER | quote }}
