apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-{{ .Values.app.container.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  # token REPO_GIT
