pipeline {
  agent any
  environment {
        
        NAMESPACE="miportfolio"
        DOCKER_IMAGE = "morgadoberruezo/portfolio"
        DOCKER_TAG = "latest"
        DOCKER_CREDENTIALS_ID = "dockerhub-cred"
        DOCKER_USER="morgadoberruezo"
        DOCKER_PASS="Claudia2009?"
        REPO="https://github.com/morgadodesarrollador/portfolioHelm.git"
  }
  stages {
    stage('Docker Login1') {
      steps {
        withCredentials([usernamePassword(
            credentialsId: "${DOCKER_CREDENTIALS_ID}",
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
        )]) {
          script {
            sh """
                echo $DOCKER_USER, $DOCKER_PASS
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            """
          }
        }
      }
    }
    //Clona el repo donde está el Jenkinsfile (el mismo que configuraste en el job).
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
  }
}
