services:
  web:
    build: 
      context: .. #portfolio
      dockerfile: deploy/Dockerfile
      args: #variables en DFILE para la construccion (build) de la imagen
        - USUARIO=pepe
        - PASSWORD=1234
    container_name: ctportfolio
    ports:
      - "8810:80"

