replicaCount: 2

image:
  repository: n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

n8n:
  encryptionKey: "super-secret-key"

extraEnv:
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: admin
  - name: N8N_BASIC_AUTH_PASSWORD
    value: admin123

  - name: N8N_HOST
    value: n8n.jamorgado.es
  - name: N8N_PROTOCOL
    value: https
  - name: WEBHOOK_URL
    value: https://n8n.jamorgado.es/

persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: traefik

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  hosts:
    - host: n8n.jamorgado.es
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - n8n.jamorgado.es
      secretName: n8n-tls