replicaCount: 1

image:
  repository: n8nio/n8n
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5678

main:
  extraEnv:
    - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
      value: "true"

    - name: N8N_HOST
      value: n8n.jamorgado.es

    - name: N8N_PORT
      value: "5678"

    - name: N8N_PROTOCOL
      value: https

    - name: NODE_ENV
      value: production

    - name: WEBHOOK_URL
      value: https://n8n.jamorgado.es/

    - name: GENERIC_TIMEZONE
      value: Europe/Madrid

    - name: TZ
      value: Europe/Madrid

    - name: N8N_RUNNERS_ENABLED
      value: "true"

    - name: N8N_SECURE_COOKIE
      value: "false"

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: true
  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

  hosts:
    - host: n8n.jamorgado.es
      paths:
        - path: /
          pathType: Prefix

  tls:
    - hosts:
        - n8n.jamorgado.es
      secretName: n8n-tls